name: Build macOS App

on:
  push:
    branches: [ main ] # Trigger on pushes to main
    tags:
      - 'v*' # Trigger on version tags like v1.0, v2.1.3
  pull_request:
    branches: [ main ] # Optional: Trigger on PRs to main
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build macOS App Bundle
    runs-on: macos-latest # Use the latest macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure py2app is installed if not in requirements.txt
          pip install py2app

      - name: Run build script
        run: python build_app.py # Execute your build script

      - name: Upload macOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TurboSync-macOS-App # Name of the artifact zip file
          path: dist/TurboSync.app # Path to the built .app bundle
          if-no-files-found: error # Fail if the .app isn't found
