name: Build and Release macOS App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    name: Build macOS Application
    runs-on: macos-latest # Use a macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install fswatch (system dependency)
        run: brew install fswatch

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare .env file
        run: cp dist/.env.template .env # Copy template to .env

      - name: Build the application
        run: python build_app.py # Assuming this script creates the .app bundle

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TurboSync-macOS-App
          path: dist/TurboSync.app # Assuming the app is built into the dist directory
          if-no-files-found: error # Fail if the app bundle isn't found

      - name: Create Release and Upload Asset
        if: startsWith(github.ref, 'refs/tags/') # Only run for tag pushes
        uses: softprops/action-gh-release@v1
        with:
          files: dist/TurboSync.app # Path to the asset to upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
