name: Build macOS App

on:
  push:
    branches: [ main ] # Trigger on pushes to main
    tags:
      - 'v*' # Trigger on version tags like v1.0, v2.1.3
  pull_request:
    branches: [ main ] # Optional: Trigger on PRs to main
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    name: Build macOS App Bundle
    runs-on: macos-latest # Use the latest macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure py2app is installed if not in requirements.txt
          pip install py2app

      - name: Run build script
        run: python build_app.py --non-interactive --install-fswatch # Execute build script non-interactively
        
      # Fix permissions on the app bundle to ensure it works correctly
      - name: Fix app permissions
        run: |
          chmod -R u+w dist/TurboSync.app
          find dist/TurboSync.app -type f -name "*.so" -exec chmod +x {} \;
          find dist/TurboSync.app -type f -name "*.dylib" -exec chmod +x {} \;
          chmod +x dist/TurboSync.app/Contents/MacOS/TurboSync
          # Remove quarantine flag if it exists
          xattr -d com.apple.quarantine dist/TurboSync.app || true

      - name: Upload macOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TurboSync-macOS-App # Name of the artifact zip file
          path: dist/TurboSync.app # Path to the built .app bundle
          if-no-files-found: error # Fail if the .app isn't found
