name: Gitleaks Scan

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch
  workflow_dispatch: # Allow manual triggering

jobs:
  scan:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for deep scan

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          # If you have a Gitleaks config file, uncomment the following line
          # GITLEAKS_CONFIG_PATH: .gitleaks.toml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional: For reporting findings back to GitHub Security tab
